version: '3.8'

services:
  kyutai_tts:
    build:
      context: .
      dockerfile: .ci/Dockerfile
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-2}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///ros2_ws/config/cyclonedds.xml
    volumes:
      - .:/ros2_ws/src/ros2_kyutai_tts
      - ./config:/ros2_ws/config